### ISSUE TITLE
Setcap not enough with newer systemd versions

### ISSUE THREAD

**Issue by lbischof** [antoiner77/caddy-ansible#59] opened 2017-07-05 19:34 UTC
See #57. What does this mean for the future regarding systemd support? Does this always have to be activated with newer systemd versions? Is `setcap` still needed or not? What changed in systemd? I don't like the fact that the user of this module has to change multiple things for port binding to work.

Can anyone confirm this behavior?

**Comment by Notmarrco** [comment] 2017-10-06 14:48
I can confirm !

I don't know for setcap, but I had this useless error in journalctl : 
```
systemd[1]: Failed to start Caddy HTTP/2 web server.
systemd[1]: caddy.service: Unit entered failed state.
systemd[1]: caddy.service: Failed with result 'exit-code'.
``` 
And it works ok when I uncomment the capabilities lines in ```caddy.service```

```
$ systemd --version
systemd 232
```

**Comment by zx1986** [comment] 2019-04-01 10:26
confirm this too!
set caddy_user to root ...

**Comment by LorenzBischof** [comment] 2019-11-14 18:17
Closing because the repository has moved to https://github.com/caddy-ansible/caddy-ansible If this is still an issue, please reopen the issue in the new repository.

**Closed by LorenzBischof** 2019-11-14 18:17 UTC
